Repository acmucsd/sp-cerulean, pull requests merged in 2020-12, with the labels that each got.

#5 Use WHERE clause in event attendance route
  api/event.js
  package.json
Labels: enhancement

#6 Added route to verify token
  api/authentication.js
  package.json
  server.js
Labels: enhancement

#7 Add API route for average points of event attendees
  api/event.js
Labels: enhancement

#9 Add route to get event information
  api/event.js
Labels: enhancement

#8 Add homepage to frontend (no route yet)
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Header.js
  client/src/components/Home.js
  client/src/components/Login.js
Labels: enhancement

#10 Average points per event chart
  .github/workflows/build.yml
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/components/AverageChart.js
  client/src/components/Home.js
  client/src/components/Login.js
  middleware/auth.js
Labels: bug, enhancement

#11 Login System
  api/authentication.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/UserContext.js
  client/src/components/AverageChart.js
  client/src/components/Header.js
  client/src/components/Home.js
  client/src/components/Login.js
  package-lock.json
  package.json
Labels: enhancement

#14 Add route to get events within a time interval
  api/event.js
Labels: enhancement

#13 Pie chart
  api/event.js
  client/src/components/AverageChart.js
  client/src/components/Home.js
  client/src/components/PieChart.js
Labels: enhancement

#18 Production fix
  client/package-lock.json
  client/package.json
  client/src/index.js
  package-lock.json
  package.json
Labels: bug
